<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Version>2.0.0</Version>
    <Authors>Diogo Carvalho</Authors>
    <Company>GlobalBlue</Company>
    <Description>C# Client for Bitbucket Server API</Description>
    <PackageTags>bitbucket;api;client;rest</PackageTags>
    <RepositoryUrl>https://dev.global-blue.com/stash/scm/~dcarvalho/bitbucket.net.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- Enforce ConfigureAwait(false) as this is a library -->
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <!-- Analyzer to enforce ConfigureAwait(false) and other library best practices -->
    <PackageReference Include="Meziantou.Analyzer" Version="2.0.182">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
